### ISSUE TITLE
How to make ramps effect from a current value1 to another value2

### ISSUE THREAD

**Issue by billyjoker** [adafruit/Adafruit_DRV2605_Library#12]
Hi, i have been reading the list of [waveform effects](https://learn.adafruit.com/assets/72593) but i did not find a kind of effect with this condition steps as follows:

- I have a value1 [0-255]
- I set that value1 to the haptic controller
- I have a value2 [0-255]
- I would like to make a ramp effect from last value1 set, to the value2

So, how could i reach this kind of ramp with this lib? Thanks in advance

**Comment by drak7** [comment]
You'll need to use the Real-Time Playback capability of the chip. First use setMode to enter RTP mode, then use setRealtimeValue to set the desired drive amplitude.

See the datasheet (http://www.ti.com/lit/ds/symlink/drv2605.pdf) for more info.

**Comment by billyjoker** [comment]
Ok i understand, so you mean that i should set the desired drive amplitude between value1 and value2, it would be likes making manually the ramp with a linear interpolation? Something likes below:

```
value1=50; //read value before value2
value2=100; //current value read

//starts the code
setRealtimeValue(50);

for(int i=51; i<100; i++) {
setRealtimeValue(i);
}

setRealtimeValue(100);
```

**Comment by drak7** [comment]
Yep, that'll do it! You'll also want a delay between calls to setRealtimeValue.

Check out the [realtime example](https://github.com/adafruit/Adafruit_DRV2605_Library/blob/master/examples/realtime/realtime.ino). That one uses an array of value/delay pairs to do the same thing.

**Comment by billyjoker** [comment]
Ok i've checked the realtime example, so i see clearer, good!! 
One more doubt, i see that the array set the value as a hex value, should i convert my integer to hex? Always having in consideration that my max integer value would be 255 -> 0xFF

**Comment by drak7** [comment]
It'll be fine as decimal, the example may have done that just to make it clear which values are amplitude and which are delays.
