### ISSUE TITLE
Redefinition of class Adafruit_DRV2605

### ISSUE THREAD

**Issue by SirWilliamT** [adafruit/Adafruit_DRV2605_Library#15]
Adding

#include "Adafruit_DRV2605.h"

in multiple different header files in an Arduino project results in a class redefinition error for Adafruit_DRV2605.

The Adafruit_DRV2605 header file needs

 #pragma once
 
 OR
 
#ifndef _ADAFRUIT_DRV2605_H
#define _ADAFRUIT_DRV2605_H

at the top of the file.

**Comment by drak7** [comment]
Good catch, thanks! If you'd like to submit a PR for that we'll merge it. The ifndef style is preferred.
